# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

# Handle git submodules yourself
git:
  submodules: false
before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
