# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @describeIn graph_coloring Color graph using DSATUR algorithm
#' \insertCite{Brelaz:1979:NMC:359094.359101}{graphcoloring}
#' @export
graph_coloring_dsatur <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_dsatur`, adj_list)
}

#' @describeIn graph_coloring Color graph using Maximum Cardinality Search(MCS) algorithm
#' \insertCite{Palsberg:2007:RAV:1273694.1273695}{graphcoloring}
#' @export
graph_coloring_msc <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_msc`, adj_list)
}

#' @describeIn graph_coloring Color graph using Least-constraining Most-constrained eXtended RLF(lmXRLF) algorithm
#' \insertCite{Kirovski:1998:ECL:277044.277165}{graphcoloring}
#' @export
graph_coloring_lmxrlf <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_lmxrlf`, adj_list)
}

#' @describeIn graph_coloring Color graph using a hybrid of DASTUR and TabuCol algorithm
#' \insertCite{Kirovski:1998:ECL:277044.277165,Brelaz:1979:NMC:359094.359101,Hertz:1987:UTS:44141.44146}{graphcoloring}
#' @export
graph_coloring_hybrid_dsatur_tabucol <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_hybrid_dsatur_tabucol`, adj_list)
}

#' @describeIn graph_coloring Color graph using a hybrid of lmXRLF and TabuCol algorithm
#' \insertCite{Kirovski:1998:ECL:277044.277165,Hertz:1987:UTS:44141.44146}{graphcoloring}
#' @export
graph_coloring_hybrid_lmxrlf_tabucol <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_hybrid_lmxrlf_tabucol`, adj_list)
}

#' @describeIn graph_coloring Color graph using TabuCol algorithm
#' \insertCite{Hertz:1987:UTS:44141.44146}{graphcoloring}
#' @export
graph_coloring_tabucol <- function(adj_list, k, tabu_size = 25L, rep = 100L, nbmax = 1000L) {
    .Call(`_graphcoloring_graph_coloring_tabucol`, adj_list, k, tabu_size, rep, nbmax)
}

