# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

graph_coloring_dsatur <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_dsatur`, adj_list)
}

graph_coloring_msc <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_msc`, adj_list)
}

graph_coloring_lmxrlf <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_lmxrlf`, adj_list)
}

graph_coloring_hybrid_dsatur <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_hybrid_dsatur`, adj_list)
}

graph_coloring_hybrid_tabucol <- function(adj_list) {
    .Call(`_graphcoloring_graph_coloring_hybrid_tabucol`, adj_list)
}

